execution:
    uuid: b01cc8bf-1c67-42e0-955c-d29a9af30713
    runtime:
        start: 2024-11-28T23:21:17.623142+11:00
        end: 2024-11-28T23:21:20.475781+11:00
        duration: 2 seconds, and 852639 microseconds
    execution_context:
        type: synchronous

action:
    type: method
    plugin: !ref 'environment:plugins:feature-table'
    action: filter_features
    inputs:
    -   table: 9b10f502-3275-40bc-b0fe-d8cbcc90f461
    parameters:
    -   min_frequency: 3000
    -   max_frequency: null
    -   min_samples: 100
    -   max_samples: null
    -   metadata: null
    -   where: null
    -   exclude_ids: false
    -   filter_empty_samples: true
    output-name: filtered_table

transformers:
    inputs:
        table:
        -   from: BIOMV210DirFmt
            to: biom.table:Table
            plugin: !ref 'environment:plugins:types'
            citations:
            - !cite 'view|types:2023.7.0|BIOMV210DirFmt|0'
            - !cite 'view|types:2023.7.0|biom.table:Table|0'
    output:
    -   from: biom.table:Table
        to: BIOMV210DirFmt
        plugin: !ref 'environment:plugins:types'
        citations:
        - !cite 'view|types:2023.7.0|biom.table:Table|0'
        - !cite 'view|types:2023.7.0|BIOMV210DirFmt|0'

environment:
    platform: linux-x86_64
    python: |-
        3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:46:39)
        [GCC 10.4.0]
    framework:
        version: 2023.7.0
        website: https://qiime2.org
        citations:
        - !cite 'framework|qiime2:2023.7.0|0'
    plugins:
        types:
            version: 2023.7.0
            website: https://github.com/qiime2/q2-types
        feature-table:
            version: 2023.7.0
            website: https://github.com/qiime2/q2-feature-table
    python-packages:
        Brotli: 1.0.9
        Cython: 3.0.2
        DendroPy: 4.5.2
        Jinja2: 3.1.2
        Markdown: '3.6'
        MarkupSafe: 2.1.3
        MiniSom: 2.3.2
        Pillow: 9.4.0
        PyJWT: 2.8.0
        PyNaCl: 1.5.0
        PyQt5: 5.15.7
        PyQt5-sip: 12.11.0
        PySocks: 1.7.1
        PyYAML: 6.0.1
        Pygments: 2.16.1
        Send2Trash: 1.8.2
        Theano: 1.0.5
        absl-py: 2.1.0
        altair: 5.0.1
        anyio: 3.7.1
        appdirs: 1.4.4
        argcomplete: 3.1.1
        argon2-cffi: 23.1.0
        argon2-cffi-bindings: 21.2.0
        arrow: 1.2.3
        astor: 0.8.1
        asttokens: 2.2.1
        astunparse: 1.6.3
        atpublic: 3.0.1
        attrs: 23.1.0
        backcall: 0.2.0
        backports.functools-lru-cache: 1.6.5
        backports.zoneinfo: 0.2.1
        bcrypt: 3.2.2
        beautifulsoup4: 4.12.2
        bibtexparser: 1.4.0
        bigsimr: 0.1.1
        biom-format: 2.1.14
        bleach: 6.0.0
        bokeh: 3.1.1
        cachecontrol: 0.13.1
        cached-property: 1.5.2
        cachetools: 5.3.3
        certifi: 2024.8.30
        cffi: 1.15.1
        charset-normalizer: 3.2.0
        click: 8.1.7
        colorama: 0.4.6
        comm: 0.1.4
        conda-pack: 0.7.0
        configparser: 7.0.0
        contourpy: 1.1.0
        cryptography: 39.0.0
        cutadapt: '4.4'
        cycler: 0.11.0
        deblur: 1.1.1
        debugpy: 1.6.8
        decorator: 4.4.2
        deepmg: 1.0.33
        defusedxml: 0.7.1
        dill: 0.3.7
        dnaio: 0.10.0
        emperor: 1.0.3
        entrypoints: '0.4'
        exceptiongroup: 1.1.3
        executing: 1.2.0
        fastcluster: 1.2.6
        fastjsonschema: 2.18.0
        flatbuffers: 24.3.25
        flufl.lock: '7.1'
        fonttools: 4.42.1
        formulaic: 0.6.4
        fqdn: 1.5.1
        future: 0.18.3
        gast: 0.4.0
        globus-sdk: 3.27.0
        gneiss: 0.4.6
        google-auth: 2.31.0
        google-auth-oauthlib: 1.0.0
        google-pasta: 0.2.0
        graphlib-backport: 1.0.3
        grpcio: 1.64.1
        h5py: 3.8.0
        hdmedians: 0.14.2
        idna: '3.4'
        ijson: 3.2.3
        importlib-metadata: 6.8.0
        importlib-resources: 6.0.1
        iniconfig: 2.0.0
        interface-meta: 1.3.0
        iow: 1.0.5
        ipykernel: 6.25.1
        ipython: 8.12.2
        ipython-genutils: 0.2.0
        ipywidgets: 8.1.0
        isal: 1.2.0
        isoduration: 20.11.0
        jedi: 0.19.0
        joblib: 1.3.2
        jsonpointer: '2.0'
        jsonschema: 4.19.0
        jsonschema-specifications: 2023.7.1
        julia: 0.6.2
        jupyter-client: 7.4.9
        jupyter-core: 5.3.0
        jupyter-events: 0.7.0
        jupyter-server: 2.7.1
        jupyter-server-terminals: 0.4.4
        jupyterlab-pygments: 0.2.2
        jupyterlab-widgets: 3.0.8
        keras: 2.13.1
        keras-sequential-ascii: 0.1.1
        kiwisolver: 1.4.5
        libclang: 18.1.1
        llvmlite: 0.40.1
        lockfile: 0.12.2
        lxml: 4.9.2
        lz4: 4.3.2
        matplotlib: 3.6.0
        matplotlib-inline: 0.1.6
        mistune: 3.0.1
        msgpack: 1.0.5
        munkres: 1.1.4
        mypy: 1.5.1
        mypy-extensions: 1.0.0
        natsort: 8.4.0
        nbclassic: 1.0.0
        nbclient: 0.8.0
        nbconvert: 7.7.4
        nbformat: 5.9.2
        nest-asyncio: 1.5.6
        networkx: 2.6.3
        nlopt: 2.7.1
        nose: 1.3.7
        notebook: 6.5.5
        notebook-shim: 0.2.3
        numba: 0.57.1
        numpy: 1.24.3
        nxt-gem: 2.0.1
        oauthlib: 3.2.2
        opt-einsum: 3.3.0
        overrides: 7.4.0
        packaging: '23.1'
        pandas: 1.5.3
        pandocfilters: 1.5.0
        paramiko: 3.3.1
        parsl: 2023.8.28
        parso: 0.8.3
        patsy: 0.5.3
        pexpect: 4.8.0
        pickleshare: 0.7.5
        pip: 23.2.1
        pkgutil-resolve-name: 1.3.10
        platformdirs: 3.10.0
        pluggy: 1.3.0
        ply: '3.11'
        pooch: 1.7.0
        prometheus-client: 0.17.1
        prompt-toolkit: 3.0.39
        protobuf: 4.25.3
        provenance-lib: 2023.7.1
        psutil: 5.9.5
        ptyprocess: 0.7.0
        pure-eval: 0.2.2
        pyasn1: 0.6.0
        pyasn1-modules: 0.4.0
        pycparser: '2.21'
        pynndescent: 0.5.10
        pyparsing: 3.1.1
        pytest: 7.4.0
        python-dateutil: 2.8.2
        python-json-logger: 2.0.7
        pytz: 2023.3.post1
        pyzmq: 24.0.1
        q2-alignment: 2023.7.0
        q2-composition: 2023.7.0
        q2-cutadapt: 2023.7.0
        q2-dada2: 2023.7.0
        q2-deblur: 2023.7.0
        q2-demux: 2023.7.0
        q2-diversity: 2023.7.0
        q2-diversity-lib: 2023.7.0
        q2-emperor: 2023.7.0
        q2-feature-classifier: 2023.7.0
        q2-feature-table: 2023.7.0
        q2-fragment-insertion: 2023.7.0
        q2-gneiss: 2023.7.0
        q2-longitudinal: 2023.7.0
        q2-makarsa: 0.0.1.dev0
        q2-metadata: 2023.7.0
        q2-mystery-stew: 2023.7.0
        q2-phylogeny: 2023.7.0
        q2-quality-control: 2023.7.0
        q2-quality-filter: 2023.7.0
        q2-sample-classifier: 2023.7.0
        q2-taxa: 2023.7.0
        q2-types: 2023.7.0
        q2-vsearch: 2023.7.0
        q2cli: 2023.7.0
        q2galaxy: 2023.7.0
        q2templates: 2023.7.0
        qiime2: 2023.7.0
        referencing: 0.30.2
        requests: 2.31.0
        requests-oauthlib: 2.0.0
        rfc3339-validator: 0.1.4
        rfc3986-validator: 0.1.1
        rpds-py: 0.10.0
        rpy2: 3.5.16
        rsa: '4.9'
        scikit-bio: 0.5.8
        scikit-learn: 0.24.1
        scipy: 1.10.0
        seaborn: 0.12.2
        sepp: 4.3.10
        setproctitle: 1.3.2
        setuptools: 68.1.2
        sip: 6.7.11
        six: 1.16.0
        sniffio: 1.3.0
        soupsieve: 2.3.2.post1
        stack-data: 0.6.2
        statsmodels: 0.14.0
        tblib: 1.7.0
        tensorboard: 2.13.0
        tensorboard-data-server: 0.7.2
        tensorflow: 2.13.1
        tensorflow-estimator: 2.13.0
        tensorflow-io-gcs-filesystem: 0.34.0
        termcolor: 2.4.0
        terminado: 0.17.1
        threadpoolctl: 3.2.0
        tinycss2: 1.2.1
        toml: 0.10.2
        tomli: 2.0.1
        tomlkit: 0.12.1
        toolz: 0.12.0
        tornado: 6.3.3
        tqdm: 4.66.1
        traitlets: 5.9.0
        typeguard: 2.13.3
        typing-extensions: 4.5.0
        typing-utils: 0.1.0
        tzlocal: '2.1'
        umap-learn: 0.5.3
        unicodedata2: 15.0.0
        unifrac: 1.3.0
        uri-template: 1.3.0
        urllib3: 2.0.4
        venny4py: 1.0.1
        wcwidth: 0.2.6
        webcolors: '1.13'
        webencodings: 0.5.1
        websocket-client: 1.6.2
        werkzeug: 3.0.3
        wheel: 0.41.2
        widgetsnbextension: 4.0.8
        wrapt: 1.15.0
        xmltodict: 0.13.0
        xopen: 1.7.0
        xyzservices: 2023.7.0
        yq: 3.2.2
        zipp: 3.16.2
        zstandard: 0.19.0
